name: View Disk in Docker

on: [push]

defaults:
  run:
    shell: bash
  volumes:
    - /usr/lib/google-cloud-sdk:/usr/lib/google-cloud-sdk
    - /usr/local/lib/android:/usr/local/lib/android
    - /usr/share/dotnet:/usr/share/dotnet

jobs:
  in-docker:
    runs-on: ubuntu-latest
    container:
      image: cqs21/asterinas:0.17.0-20260114
      options: --device=/dev/kvm --privileged
    steps:
      - uses: actions/checkout@v4
      - run: df -alh
      - run: rm -rf /usr/lib/google-cloud-sdk/* /usr/local/lib/android/* /usr/share/dotnet/*
      - run: df -alh

