name: View Disk

on: [push]

jobs:
  direct:
    runs-on:
      group: Default
      labels: dev-runner
    steps:
      - uses: actions/checkout@v4
        with:
          repository: cqs21/asterinas
          ref: main
          fetch-depth: 1
      - uses: kohlerdominik/docker-run-action@v2.0.0
        with:
          image: asterinas/asterinas:0.17.2-20260407
          options: --privileged
          volumes: |
            ${{ github.workspace }}:/root/asterinas
            /dev:/dev
          run: |
            df -alh

